name: cd-tag

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: build go binaries and release to github
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set image tag
        run: |
          set -euo pipefail
          TAGV="${GITHUB_REF#refs/*/}"
          TAG="${TAGV/v}"
          echo "TAG=${TAG}" >> "${GITHUB_ENV}"
        shell: bash

      - name: build scratch images and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.scratch
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

      - name: build alpine images and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}-alpine
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

